### ISSUE TITLE
[of_stats] @rest not registering staticmethod endpoints

### ISSUE THREAD

**Issue by rmotitsuki** [kytos/legacy#300]
All `@staticmethod` endpoints are not being registered using the `@rest`.

I´ve made a quick test and removing the @staticmethod from the [main.py](https://github.com/kytos/legacy/blob/88fe3764d160e638bb9875c00d10821d5ef25f82/napps/kytos/of_stats/main.py#L61) file Kytos registered the api endpoint correctly.

**Comment by cemsbr** [comment]
We are going to release kytos/of_stats soon. Meanwhile, there's the legacy/of_stats without the rest decorator.

About the `@rest` decorator and `@staticmethod`, you should first write `@staticmethod` and use the `rest` decorator right before the method.

**Comment by cemsbr** [comment]
It will be solved by either #303 or kytos/kytos#599.
